#define kAppKey             @"1076507647"
#define kAppSecret          @"c3fa815939559399fdb116f76784c0b5"
#define kAppRedirectURL     @"http://www.weibo.com"

enum {
    MOCAFE_NEW = 0,
    MOCAFE_CAFE,
    MOCAFE_TEA ,
    MOCAFE_FOOD ,
    MOCAFE_ACTIVITIES ,
    MOCAFE_WEIBO ,
    MOCAFE_ABOUT ,
};
typedef NSUInteger MO_CAFE_TYPE;

#define Ma_VIEW_INDEX 1000

#define MA_TOOLBAR_HEIGHT 44

#define MA_ART_FRAME_Y 100

#define ZOOM_VIEW_TAG 100
#define MA_MAX_ZOOM_RATE 2.0
#define MA_MIN_ZOOM_RATE 1.0

#define MA_ART_WIDTH 240
#define MA_ART_WIDTH_DELTA 40


#define MA_CELL_MIN_HEIGHT 55.0f
#define MA_CELL_GAP 5
#define MA_CELL_IMG_SIZE 48

#define MA_CELL_NAME_WIDTH 160
#define MA_CELL_NAME_HEIGHT 20

#define MA_CELL_TIME_WIDTH 100
#define MA_CELL_TIME_HEIGHT 15

#define MA_CELL_MESSAGE_WIDTH 250
#define MA_CELL_MESSAGE_HEIGHT 90

#define MA_CELL_MESSAGE_PICT_SIZE 60

#define MA_CELL_MESSAGE_LINE_WIDTH 1
#define MA_CELL_MESSAGE_WIDTH_OF_RETANGLE 248
#define MA_CELL_MESSAGE_WIDTH_OF_POPUP_TRIANGLE 13
#define MA_CELL_MESSAGE_HEIGHT_OF_POPUP_TRIANGLE 6
#define MA_CELL_MESSAGE_X_DELTA_OF_POPUP_TRIANGLE 15
#define MA_CELL_MESSAGE_X_BORDER 3
#define MA_CELL_MESSAGE_Y_BORDER 9
#define MA_CELL_MESSAGE_BORDER_RADIUS 3
#define MA_CELL_MESSAGE_RETANGLE_TEXT_WIDTH 240

#define MA_CELL_STATUS_WIDTH 150

#define MA_MINUTE 60
#define MA_HOUR   (60 * MA_MINUTE)
#define MA_DAY    (24 * MA_HOUR)
#define MA_5_DAYS (5 * MA_DAY)
#define MA_WEEK   (7 * MA_DAY)
#define MA_MONTH  (30.5 * MA_DAY)
#define MA_YEAR   (365 * MA_DAY)

#define MA_MORE_CELL_LABLE_TAG 9800

#define MA_LIST_VIEW_ROW_HEIGHT 370

#define MA_LIST_CELL_GAP 20
#define MA_LIST_CELL_WIDTH 280
#define MA_LIST_CELL_HEIGHT 350
#define MA_LIST_CELL_INNER_GAP 5
#define MA_LIST_CELL_INNER_WIDTH 270
#define MA_LIST_CELL_INNER_HEIGHT 260
