#define kAppKey             @"3111231318"
#define kAppSecret          @"ade7c8775fcb3b823438d83e290db108"
#define kAppRedirectURI     @"http://google.com.hk"


#define MA_CELL_MIN_HEIGHT 60.0f

#define MA_CELL_GAP 5
#define MA_CELL_IMG_SIZE 48

#define MA_CELL_NAME_WIDTH 150
#define MA_CELL_NAME_HEIGHT 20

#define MA_CELL_TIME_WIDTH 100
#define MA_CELL_TIME_HEIGHT 15

#define MA_CELL_MESSAGE_WIDTH 250
#define MA_CELL_MESSAGE_HEIGHT 90

#define MA_CELL_MESSAGE_PICT_SIZE 60

#define MA_CELL_MESSAGE_LINE_WIDTH 1
#define MA_CELL_MESSAGE_WIDTH_OF_RETANGLE 248
#define MA_CELL_MESSAGE_WIDTH_OF_POPUP_TRIANGLE 13
#define MA_CELL_MESSAGE_HEIGHT_OF_POPUP_TRIANGLE 6
#define MA_CELL_MESSAGE_X_DELTA_OF_POPUP_TRIANGLE 15
#define MA_CELL_MESSAGE_X_BORDER 3
#define MA_CELL_MESSAGE_Y_BORDER 9
#define MA_CELL_MESSAGE_BORDER_RADIUS 3

#define MA_MINUTE 60
#define MA_HOUR   (60 * MA_MINUTE)
#define MA_DAY    (24 * MA_HOUR)
#define MA_5_DAYS (5 * MA_DAY)
#define MA_WEEK   (7 * MA_DAY)
#define MA_MONTH  (30.5 * MA_DAY)
#define MA_YEAR   (365 * MA_DAY)
